jwt:
  secret: "afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf"


spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8081
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect




