spring:
  application:
    name: RatingService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Postgress@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8083
