spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      mvc:
       routes:
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/rating/**

        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8010
